services:
  go:
    container_name: go-huma
    volumes:
      - ./app/:/app/
    tty: true
    build:
      dockerfile: ./app/Dockerfile
      target: dev
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:17-alpine
    container_name: postgres-huma
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: ${POSTGRES_DATABASE}
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-huma
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres