services:
  go:
    container_name: go-huma
    volumes:
      - ./app/:/app/
    tty: true
    build:
      dockerfile: ./app/Dockerfile
      target: dev
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:17-alpine
    container_name: postgres-huma
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    env_file:
      - ./app/.env
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-huma
    ports:
      - 8081:80
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    env_file:
      - ./app/.env
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres