services:
  go:
    container_name: go-huma-sqlc
    volumes:
      - ./app/:/app/
    tty: true
    build:
      dockerfile: ./app/Dockerfile
      target: dev
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:17-alpine
    container_name: go-huma-sqlc-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - ./app/.env
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: go-huma-sqlc-pgadmin
    ports:
      - 8081:80
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    env_file:
      - ./app/.env
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-volume:
  pgadmin-volume: